function count = ScoreGetWorkstateCount(searchResultId, workflowState, objectType, userId)
    count = -1;
    switch objectType
        case 0 %Study
            count = ScoreQueryRun(['SELECT COUNT(SearchResultStudyId) FROM [SearchResult_Study] ' ... 
            ' WHERE WorkflowState=' num2str(workflowState) ... 
            ' AND SearchResultId = ' num2str(searchResultId)]);    
        case 1 %Description
            count = ScoreQueryRun(['SELECT COUNT(SearchResultDescriptionId) FROM [SearchResult_Description] ' ... 
            ' WHERE WorkflowState=' num2str(workflowState) ... 
            ' AND SearchResultId = ' num2str(searchResultId)]);    
        case 2 %Recording
            count = ScoreQueryRun(['SELECT COUNT(SearchResultRecordingId) FROM [SearchResult_Recording] ' ... 
            ' WHERE WorkflowState=' num2str(workflowState) ... 
            ' AND SearchResultId = ' num2str(searchResultId)]);    
        case 3 %EventCoding
            count = ScoreQueryRun(['SELECT COUNT(SearchResultEventcodingId) FROM [SearchResult_EventCoding] ' ... 
            ' WHERE WorkflowState=' num2str(workflowState) ... 
            ' AND SearchResultId = ' num2str(searchResultId)]);    
        case 4 %Event
            count = ScoreQueryRun(['SELECT COUNT(SearchResult_Event.SearchResultEventId) FROM [SearchResult_Event] ' ... 
            ' INNER JOIN SearchResult_Event_UserWorkState ON SearchResult_Event.SearchResultEventId = SearchResult_Event_UserWorkState.SearchResultEventId' ...
            ' WHERE SearchResult_Event_UserWorkState.Workstate=' num2str(workflowState) ... 
            ' AND SearchResult_Event.SearchResultId = ' num2str(searchResultId)]);    
        otherwise
            error('Unknown type of object to count');
    end        
	count = count.x;    
end
