function ScoreSetStudyFileStatus(searchResultStudyId, fileStatusValue)  
  query = ['UPDATE [dbo].[SearchResult_Study] SET FileState = ' ...
      num2str(fileStatusValue) ...
      ' WHERE SearchResultStudyId = ' ...
      num2str(searchResultStudyId)];
  
  ScoreQueryRun(query);  
end