function ScoreSetStudyWorkStatus(searchResultStudyId, workStatusValue)  
  query = ['UPDATE [dbo].[SearchResult_Study] SET WorkflowState = ' ...
      num2str(workStatusValue) ...
      ' WHERE SearchResultStudyId = ' ...
      num2str(searchResultStudyId)];
  
  ScoreQueryRun(query);  
end