function count = ScoreWorkstateCount(searchResultStudyId, workflowState)
    count = ScoreQueryRun(['SELECT COUNT([SearchResult_Study].[SearchResultStudyId]) FROM [SearchResult_Study] ' ... 
        ' WHERE WorkflowState=' num2str(workflowState) ... 
        ' AND SearchResultId = ' num2str(searchResultStudyId)]);    
end
