function ScoreCheckOneStudyFiles(searchResultStudyId)
    query = ['SELECT  [RecordingId]' ...
      ' ,Study.StudyId' ...
	  ' ,SearchResult_Study.SearchResultId' ...
	  ' ,SearchResult_Study.SearchResultStudyId' ...
      ' ,CONVERT(varchar(255), FileName) AS FileName' ...
      ' ,CONVERT(varchar(255), FilePath) AS FileName' ...      
	  ' ,SearchResult_Study.FileState' ...
      ' FROM [HolbergAnon].[dbo].[Recording] ' ...
      ' INNER JOIN Study ON Recording.StudyId = Study.StudyId ' ...
      ' INNER JOIN SearchResult_Study ON Study.StudyId = SearchResult_Study.StudyId ' ...
      ' WHERE Recording.IsDeleted <> 1 AND Study.IsDeleted <> 1 AND SearchResult_Study.SearchResultStudyId = ' ...
      num2str(searchResultStudyId) ]; 
  
  recording = ScoreQueryRun(query);  
  if strcmp(recording, 'No Data')
      ScoreSetStudyFileStatus(searchResultStudyId, -1);
  else  
      fullPath = strcat(recording(6), '\', recording(5));
      if not(exist(fullPath{1}, 'file') == 2)
          ScoreSetStudyFileStatus(searchResultStudyId, -1);
      elseif not(recording(7)== -1)
          ScoreSetStudyFileStatus(searchResultStudyId, 1);
      end  
   end
end