function data = ScoreGetAnnotationsForOneEvent(searchResultEventId, searchResultId)
    [scoreUserId, scoreUserName] = ScoreGetCurrentUser(1);
    sql = [...
        
    'SELECT ' ...
    'SearchResult_AnnotationConfig.FieldName, '...    
    'CAST(CASE ' ...
    '   WHEN SearchResult_AnnotationConfig.HasInteger=1 THEN ''Int''  ' ...    
    '   WHEN SearchResult_AnnotationConfig.HasFloat=1 THEN ''Float''  ' ...    
    '   WHEN SearchResult_AnnotationConfig.HasString=1 THEN ''Text''  ' ...    
    '   WHEN SearchResult_AnnotationConfig.HasBit=1 THEN ''Bit'' ' ...    
    '   WHEN SearchResult_AnnotationConfig.HasBlob=1 THEN ''Blob''  ' ...    
    '   ELSE ''unknown'' END AS varchar(50))' ...    
    ' AS FieldType,' ...    
    'CONCAT(' ...
    ' SearchResult_Event_Annotation.ValueInt,'...
    ' SearchResult_Event_Annotation.ValueFloat,'...
    ' SearchResult_Event_Annotation.ValueText,'...
    ' SearchResult_Event_Annotation.ValueBit,'...
    ' SearchResult_Event_Annotation.ValueBlob'...
    ') AS Value,' ...      
    'SearchResult_AnnotationConfig.SearchResultAnnotationConfigId ' ...
    'FROM   SearchResult_AnnotationConfig ' ...
    'LEFT OUTER JOIN ' ...
	'( SELECT * '...
    '  FROM SearchResult_Event_Annotation ' ...
    '  WHERE SearchResult_Event_Annotation.UserId=' num2str(scoreUserId) ...
    '  AND SearchResult_Event_Annotation.SearchResultEventId=' num2str(searchResultEventId) ...
    '  )  AS SearchResult_Event_Annotation ' ...
	'ON  SearchResult_Event_Annotation.SearchResultAnnotationConfigId = SearchResult_AnnotationConfig.SearchResultAnnotationConfigId '...
	'WHERE SearchResult_AnnotationConfig.SearchResultId=' num2str(searchResultId) ...
    ];
    
    
    %disp(sql);
    data = ScoreQueryRun(sql);        
end
