function data = ScoreGetAnnotationsForOneEvent(searchResultEventId, searchResultId)
    [scoreUserId, scoreUserName] = ScoreGetCurrentUser(1);
    sql = [...
        
    'SELECT ' ...
    'SearchResult_AnnotationConfig.FieldName, '...    
    'SearchResult_Event_Annotation.ValueInt, ' ...
    'SearchResult_Event_Annotation.ValueFloat, ' ...
    'SearchResult_Event_Annotation.ValueText, ' ...
    'SearchResult_Event_Annotation.ValueBit, ' ...
    'SearchResult_Event_Annotation.ValueBlob, ' ...
    'SearchResult_AnnotationConfig.HasInteger, ' ...
    'SearchResult_AnnotationConfig.HasFloat, ' ...
    'SearchResult_AnnotationConfig.HasString, ' ...
    'SearchResult_AnnotationConfig.HasBit, ' ...
    'SearchResult_AnnotationConfig.HasBlob, ' ...
    'SearchResult_AnnotationConfig.SearchResultAnnotationConfigId ' ...
    'FROM   SearchResult_AnnotationConfig ' ...
    'LEFT OUTER JOIN ' ...
	'( SELECT * '...
    '  FROM SearchResult_Event_Annotation ' ...
    '  WHERE SearchResult_Event_Annotation.UserId=' num2str(scoreUserId) ...
    '  AND SearchResult_Event_Annotation.SearchResultEventId=' num2str(searchResultEventId) ...
    '  )  AS SearchResult_Event_Annotation ' ...
	'ON  SearchResult_Event_Annotation.SearchResultAnnotationConfigId = SearchResult_AnnotationConfig.SearchResultAnnotationConfigId '...
	'WHERE SearchResult_AnnotationConfig.SearchResultId=' num2str(searchResultId) ...
    ];
    
    
    %disp(sql);
    data = ScoreQueryRun(sql);        
end
