function data = ScoreCreateAnnotationConfig(searchResultId, fieldName, fieldComment, hasInteger, hasFloat, hasString, hasBit)
    
    sql= ...
        ['INSERT INTO [SearchResult_AnnotationConfig] ' ...
        ' (SearchResultId, AnnotationLevel, FieldName, FieldComment, HasInteger, HasFloat, HasString, HasBit) ' ...
        ' VALUES (' ...
        num2str(searchResultId) ', ' ...
        '''Event'', ' ...
        '''' fieldName ''', ' ...
        '''' fieldComment ''', ' ...
        num2str(hasInteger) ', ' ...
        num2str(hasFloat)  ', ' ...
        num2str(hasString) ', '  ...
        num2str(hasBit)  ...
        ')'];
    
    data = ScoreQueryRun(sql);
    
end