
     
function data = ScoreSetAnnotationForOneEvent(searchResultEventId, searchResultAnnotationConfigId, valueText, valueInt, valueFloat, valueBit)    

sql = ['SELECT MIN(SearchResultEventAnnotationId) FROM SearchResult_Event_Annotation ' ...
    'WHERE SearchResult_Event_Annotation.SearchResultEventId=' num2str(searchResultEventId) ...
    'AND SearchResult_Event_Annotation.SearchResultAnnotationConfigId=' num2str(searchResultAnnotationConfigId) ...
];   
existing = ScoreQueryRun(sql);
if isempty(valueInt)
    valueInt = 0;
end
if isempty(valueFloat)
    valueFloat = 0;
end

if isnan(existing.x) 
    sql = [...
    ' INSERT INTO SearchResult_Event_Annotation (SearchResultEventId, SearchResultAnnotationConfigId, ValueText, ValueInt, ValueFloat, ValueBit) ' ...
    'VALUES (' num2str(searchResultEventId) ', ' num2str(searchResultAnnotationConfigId) ...
    ', ''' valueText '''' ...
    ', ' num2str(valueInt) ...
    ', ' num2str(valueFloat) ...
    ', ' num2str(valueBit) ...
    ');']; 
    data = ScoreQueryRun(sql);        
else   
    existingId = existing.x;
    sql = ['UPDATE SearchResult_Event_Annotation SET ' ...
           '  ValueText = ''' valueText '''' ...
           ', ValueInt = ' num2str(valueInt) ...           
           ', ValueFloat = ' num2str(valueFloat) ...
           ', ValueBit = ' num2str(valueBit) ...
           'WHERE SearchResult_Event_Annotation.SearchResultEventAnnotationId = ' ...
           num2str(existingId) ];
    data = ScoreQueryRun(sql);  
end        
end
