
     
function data = ScoreSetAnnotationForOneEvent(searchResultEventId, searchResultAnnotationConfigId, valueText, valueInt, valueFloat)    

sql = ['SELECT MIN(SearchResultEventAnnotationId) FROM SearchResult_Event_Annotation ' ...
    'WHERE SearchResult_Event_Annotation.SearchResultEventId=' num2str(searchResultEventId) ...
    'AND SearchResult_Event_Annotation.SearchResultAnnotationConfigId=' num2str(searchResultAnnotationConfigId) ...
];   
existing = ScoreQueryRun(sql);
if isnan(existing.x) 
    sql = [...
    ' INSERT INTO SearchResult_Event_Annotation (SearchResultEventId, SearchResultAnnotationConfigId, ValueText, ValueInt, ValueFloat) ' ...
    'VALUES (' num2str(searchResultEventId) ', ' num2str(searchResultAnnotationConfigId) ...
    ', ''' valueText ''',' num2str(valueInt) ', ' num2str(valueFloat) ');']; 

    disp(sql);
    data = ScoreQueryRun(sql);        
else   
    existingId = existing.x;
    sql = ['UPDATE SearchResult_Event_Annotation ' ...
           'SET ValueInt = ' num2str(valueInt) ...
           ', ValueText = ''' valueText '''' ...
           ', ValueFloat = ' num2str(valueFloat) ' ' ...
           'WHERE SearchResult_Event_Annotation.SearchResultEventAnnotationId = ' ...
           num2str(existingId) ];
    disp(sql);
    data = ScoreQueryRun(sql);  
end        
end
