function text = ScoreGetOneEventTextInfo(searchResultEventId, useHTMLBreak)

    shoppingBasketQuery = ['SELECT  ' ... 
        'SearchResult_Event.SearchResultEventId, ' ...
        'EventCode.Name AS EventCodeName, ' ...
        'EventCode.Code AS EventCodeCode, ' ...
        'EventPropertyType.Lang_eng AS EventPropertyTypeName, ' ...
        'EventPropertyCode.Description AS EventPropertyCodeName ' ...
        'FROM   SearchResult_Event  INNER JOIN ' ...
        'Event ON SearchResult_Event.EventId = Event.EventId INNER JOIN ' ...
        'EventCoding ON Event.EventCodingId = EventCoding.EventCodingId INNER JOIN ' ...
        'EventCode ON EventCoding.EventCodeId = EventCode.EventCodeId  INNER JOIN ' ...  
        'EventPropertyCoding ON EventPropertyCoding.EventId = Event.EventId INNER JOIN ' ...
        'EventPropertyCode ON EventPropertyCoding.EventPropertyCodeId = EventPropertyCode.EventPropertyCodeId INNER JOIN ' ...
        'EventPropertyType ON EventPropertyCode.EventPropertyTypeId = EventPropertyType.EventPropertyTypeId ' ...
         ];
    data = ScoreQueryRun([shoppingBasketQuery ... 
        'WHERE NOT EventPropertyCode.Description = ''Undetermined'' ' ... 
        'AND SearchResult_Event.SearchResultEventId=' num2str(searchResultEventId) ]);
    
    %disp(data);
    text = [ data.EventCodeName(1) ];
    for i=1:numel(data.EventPropertyTypeName)
        if useHTMLBreak
            text = [text '<BR>'];
        end
        text = [text data.EventPropertyTypeName(i) ':' data.EventPropertyCodeName(i)];        
    end
    text = strjoin(text);
end