function count = ScoreGetFilestateCount(searchResultId, fileState, objectType)
    count = -1;
    switch objectType
        case 0 %Study
            count = ScoreQueryRun(['SELECT COUNT(SearchResultStudyId) FROM [SearchResult_Study] ' ... 
            ' WHERE FileState=' num2str(fileState) ... 
            ' AND SearchResultId = ' num2str(searchResultId)]);    
        case 1 %Description
            count = ScoreQueryRun(['SELECT COUNT(SearchResultDescriptionId) FROM [SearchResult_Description] ' ... 
            ' WHERE FileState=' num2str(fileState) ... 
            ' AND SearchResultId = ' num2str(searchResultId)]);    
        case 2 %Recording
            count = ScoreQueryRun(['SELECT COUNT(SearchResultRecordingId) FROM [SearchResult_Recording] ' ... 
            ' WHERE FileState=' num2str(fileState) ... 
            ' AND SearchResultId = ' num2str(searchResultId)]);    
        case 3 %EventCoding
            count = ScoreQueryRun(['SELECT COUNT(SearchResultEventcodingId) FROM [SearchResult_EventCoding] ' ... 
            ' WHERE FileState=' num2str(fileState) ... 
            ' AND SearchResultId = ' num2str(searchResultId)]);    
        case 4 %Event
            count = ScoreQueryRun(['SELECT COUNT(SearchResultEventId) FROM [SearchResult_Event] ' ... 
            ' WHERE FileState=' num2str(fileState) ... 
            ' AND SearchResultId = ' num2str(searchResultId)]);    
        otherwise
            error('Unknown type of object to count');
    end    
end
