function data = ScoreGetAnnotationConfig(searchResultAnnotationConfigId)
    
    data = ScoreQueryRun( ...
    ['SELECT * FROM [SearchResult_AnnotationConfig] ' ...
        'WHERE SearchResultAnnotationConfigId= ' ...
        num2str(searchResultAnnotationConfigId)]);
end