function ScoreSubsampleProject(searchResultId, number)

if number <= 0
    error('Number must be larger than zero');
end

testQuery = ['SELECT [SearchResult].SearchResultId ' ...
    'FROM SearchResult ' ...
    'WHERE [SearchResult].SearchResultId = ' num2str(searchResultId) ...
    ];
testData = ScoreQueryRun(testQuery);
if strcmp(testData,'No Data') == 0
        dupQuery1 = [...
        'INSERT INTO SearchResult ([SearchSavedId],[DatePerformed],[Comment],[UserId]) ' ...
        'SELECT [SearchSavedId],[DatePerformed],N''(sub) '' + [Comment],[UserId] '...
        'FROM SearchResult ' ...
        'WHERE SearchResultId = ' num2str(searchResultId) ...
        ];
        dupData1 = ScoreQueryRun(dupQuery1);
        
        newQuery = ['SELECT MAX([SearchResult].SearchResultId) ' ...
        'FROM SearchResult ' ...    
        ];
        newSearchId = ScoreQueryRun(newQuery);
        newSearchId = newSearchId.x;        
    
        dupQuery2 = [...
        'INSERT INTO SearchResult_Study ([SearchResultId],[StudyId],[WorkflowState],[FileState]) ' ...
        'SELECT TOP ' num2str(number) ' ' num2str(newSearchId) ',[StudyId],0,[FileState] '...
        'FROM SearchResult_Study ' ...
        'WHERE SearchResultId = ' num2str(searchResultId) ...
        ];    
        ScoreQueryRun(dupQuery2);
        
    else
        error(['SearchResultId ' num2str(searchResultId) ' not found']);
    end    
end