function ScoreSetRecordingFileStatus(searchResultRecordingId, fileStatusValue)           
    query = ['UPDATE [dbo].[SearchResult_Recording] SET FileState = ' ...
          num2str(fileStatusValue) ...
          ' WHERE SearchResultRecordingId =' ... 
          num2str(searchResultRecordingId)]; 
  
  ScoreQueryRun(query);  
end