function ScoreDeleteSearchResult(searchResultId)
    deleteQuery = [...
        'DELETE FROM SearchResult WHERE SearchResultId=' ...
        num2str(searchResultId) ...        
        ]; 
        ScoreQueryRun(deleteQuery); 
end