function text = ScoreGetOneEventLocationTextInfo(searchResultEventId, useHTMLBreak)

    shoppingBasketQuery = ['SELECT SearchResult_Event.SearchResultEventId, ' ...
        'LocationType.Lang_eng AS LocationTypeName, ' ...
        'Sensor.Name AS SensorName, ' ...
        'SensorSelectionType.Description AS SensorSelectionType ' ...
        'FROM   SearchResult_Event INNER JOIN ' ...
        'Event ON SearchResult_Event.EventId = Event.EventId INNER JOIN ' ...
        'LocationCoding ON Event.EventId = LocationCoding.EventId INNER JOIN ' ...
        'LocationSensorCoding ON LocationCoding.LocationCodingId = LocationSensorCoding.LocationCodingId INNER JOIN ' ...
        'LocationType ON LocationSensorCoding.LocationTypeId = LocationType.LocationTypeId INNER JOIN ' ...
        'Sensor ON LocationSensorCoding.SensorId = Sensor.SensorId INNER JOIN ' ...
        'SensorSelectionType ON LocationSensorCoding.SensorSelectionTypeId = SensorSelectionType.SensorSelectionTypeId ' ...
         ];
    data = ScoreQueryRun([shoppingBasketQuery ...         
        'WHERE SearchResult_Event.SearchResultEventId=' num2str(searchResultEventId) ]);
    
    %disp(data);
    text = '';
    if ~strcmp(data, 'No Data')
        text = [ data.LocationTypeName(1) ];
        for i=1:numel(data.SensorName)
            if useHTMLBreak
                text = [text '<BR>'];
            end
            text = [text data.SensorName(i) ':' data.SensorSelectionType(i)];        
        end
        text = strjoin(text);
    else
        text = 'No location info';
    end
end